MyPersonalWebsite/ServiceHost/Areas/Administration/Pages/Accounts/Roles/Create.cshtml.cs
using AccountManagement.Application.Contract.Role;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ServiceHost.Areas.Administration.Pages.Accounts.Roles
{
    public class CreateModel : PageModel
    {
        public CreateRole Command;
        private readonly IRoleApplication _roleApplication;

        public CreateModel(IRoleApplication roleApplication)
        {
            _roleApplication = roleApplication;
        }

        public void OnGet()
        {

        }


        public IActionResult OnPost(CreateRole command)
        {
            var result = _roleApplication.CreateRole(command);

            return RedirectToPage("Index");
        }
    }
}

MyPersonalWebsite/ServiceHost/Areas/Administration/Pages/Accounts/Roles/Edit.cshtml.cs
using System.Collections.Generic;
using AccountManagement.Application.Contract.Role;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace ServiceHost.Areas.Administration.Pages.Accounts.Roles
{
    public class EditModel : PageModel
    {
        public EditRole Command;
        public List<SelectListItem> Permissions = new List<SelectListItem>();
        private readonly IRoleApplication _roleApplication;



        public EditModel(IRoleApplication roleApplication)
        {
            _roleApplication = roleApplication;
        }

        public void OnGet(long id)
        {
            Command = _roleApplication.GetDetails(id);
        }

        public IActionResult OnPost(EditRole command)
        {
            var result = _roleApplication.EditRole(command);
            return RedirectToPage("Index");
        }
    }
}

MyPersonalWebsite/ServiceHost/Areas/Administration/Pages/Blog/Article/Create.cshtml.cs
using BlogManegement.Application.Contract.Article;
using BlogManegement.Application.Contract.ArticleCategory;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace ServiceHost.Areas.Administration.Pages.Blog.Article
{
    public class CreateModel : PageModel
    {
        public SelectList ArticleCategories;
        public CreateArticle Command;

        private readonly IArticleApplication _articleApplication;
        private readonly IArticleCategoryApplication _articleCategoryApplication;

        public CreateModel(IArticleCategoryApplication articleCategoryApplication, IArticleApplication articleApplication)
        {
            _articleCategoryApplication = articleCategoryApplication;
            _articleApplication = articleApplication;
        }

        public void OnGet()
        {
            ArticleCategories = new SelectList(_articleCategoryApplication
                .GetArticleCategories(), "Id", "Name");
        }

        public IActionResult OnPost(CreateArticle command)
        {
            var article = _articleApplication.Create(command);
            return RedirectToPage("./Index");
        }
    }
}

MyPersonalWebsite/ServiceHost/Areas/Administration/Pages/Blog/Article/Edit.cshtml.cs
using BlogManegement.Application.Contract.Article;
using BlogManegement.Application.Contract.ArticleCategory;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace ServiceHost.Areas.Administration.Pages.Blog.Article
{
    public class EditModel : PageModel
    {
        public SelectList ArticleCategories;
        public EditArticle Command;

        private readonly IArticleApplication _articleApplication;
        private readonly IArticleCategoryApplication _articleCategoryApplication;

        public EditModel(IArticleCategoryApplication articleCategoryApplication, IArticleApplication articleApplication)
        {
            _articleCategoryApplication = articleCategoryApplication;
            _articleApplication = articleApplication;
        }

        public void OnGet(long id)
        {
            Command = _articleApplication.GetDetails(id);
            ArticleCategories = new SelectList(_articleCategoryApplication
                .GetArticleCategories(), "Id", "Name");
        }

        public IActionResult OnPost(EditArticle command)
        {
            var article = _articleApplication.Edit(command);
            return RedirectToPage("./Index");
        }
    }
}

MyPersonalWebsite/ServiceHost/Areas/Administration/Pages/Project/Projects/Create.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using ProjectManagement.Application.Contract.Project;
using ProjectManagement.Application.Contract.ProjectCategory;

namespace ServiceHost.Areas.Administration.Pages.Project.Projects
{
    public class CreateModel : PageModel
    {
        public SelectList ProjectCategories;
        public CreateProject Command;

        private readonly IProjectApplication _projectApplication;
        private readonly IProjectCategoryApplication _projectCategoryApplication;

        public CreateModel(IProjectCategoryApplication projectCategoryApplication, IProjectApplication projectApplication)
        {
            _projectCategoryApplication = projectCategoryApplication;
            _projectApplication = projectApplication;
        }

        public void OnGet()
        {
            ProjectCategories = new SelectList(_projectCategoryApplication
                .GetProjectCategory(), "Id", "Name");
        }

        public IActionResult OnPost(CreateProject command)
        {
            var project = _projectApplication.Create(command);
            return RedirectToPage("./Index");
        }
    }
}

MyPersonalWebsite/ServiceHost/Areas/Administration/Pages/Project/Projects/Edit.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using ProjectManagement.Application.Contract.Project;
using ProjectManagement.Application.Contract.ProjectCategory;

namespace ServiceHost.Areas.Administration.Pages.Project.Projects
{
    public class EditModel : PageModel
    {
        public SelectList ProjectCategories;
        public EditProject Command;

        private readonly IProjectApplication _projectApplication;
        private readonly IProjectCategoryApplication _projectCategoryApplication;

        public EditModel(IProjectApplication projectApplication, IProjectCategoryApplication projectCategoryApplication)
        {
            _projectApplication = projectApplication;
            _projectCategoryApplication = projectCategoryApplication;
        }


        public void OnGet(long id)
        {
            Command = _projectApplication.GetDetails(id);
            ProjectCategories = new SelectList(_projectCategoryApplication
                .GetProjectCategory(), "Id", "Name");
        }

        public IActionResult OnPost(EditProject command)
        {
            var project = _projectApplication.Edit(command);
            return RedirectToPage("./Index");
        }
    }
}

MyPersonalWebsite/ServiceHost/Areas/Administration/Pages/Services/Clients/Index.cshtml.cs
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ServiceManagement.Application.Contract.ClientsOpinion;

namespace ServiceHost.Areas.Administration.Pages.Services.Clients
{
    public class IndexModel : PageModel
    {
        [TempData]
        public string Message { get; set; }

        public List<ClientsOpinionViewModel> ClientsOpinion;

        private readonly IClientsOpinionApplication _clientsOpinionApplication;

        public IndexModel(IClientsOpinionApplication clientsOpinionApplication)
        {
            _clientsOpinionApplication = clientsOpinionApplication;

        }


        public void OnGet()
        {

            ClientsOpinion = _clientsOpinionApplication.GetList();
        }

        public IActionResult OnGetCreate()
        {
            var command = new CreateClientsOpinion();
            return Partial("./Create", command);

        }

        public JsonResult OnPostCreate(CreateClientsOpinion command)
        {
            var result = _clientsOpinionApplication.Create(command);
            return new JsonResult(result);
        }

        public IActionResult OnGetEdit(long id)
        {
            var slide = _clientsOpinionApplication.GetDetails(id);
            return Partial("Edit", slide);
        }

        public JsonResult OnPostEdit(EditClientsOpinion command)
        {
            var result = _clientsOpinionApplication.Edit(command);
            return new JsonResult(result);
        }


        public IActionResult OnGetRemove(long id)
        {
            var result = _clientsOpinionApplication.Remove(id);

            if (result.IsSuccedded)
            {
                return RedirectToPage("./Index");
            }

            Message = result.Message;
            return RedirectToPage("./Index");

        }
        public IActionResult OnGetRestore(long id)
        {
            var result = _clientsOpinionApplication.Restore(id);
            if (result.IsSuccedded)
            {
                return RedirectToPage("./Index");
            }

            Message = result.Message;
            return RedirectToPage("./Index");
        }
    }
}

MyPersonalWebsite/ServiceHost/Areas/Administration/Pages/Services/ContactMeMessages/Index.cshtml.cs
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ServiceManagement.Application.Contract.ContactMe;

namespace ServiceHost.Areas.Administration.Pages.Services.ContactMeMessages
{
    public class IndexModel : PageModel
    {
        [TempData]
        public string Message { get; set; }

        public List<ContactMeViewModel> ContactMe;

        private readonly IContactMeApplication _contactMeApplication;

        public IndexModel(IContactMeApplication contactMeApplication)
        {
            _contactMeApplication = contactMeApplication;

        }


        public void OnGet()
        {

            ContactMe = _contactMeApplication.GetList();
        }

        public IActionResult OnGetGetInformation(long id)
        {
            var info = _contactMeApplication.GetInformationBy(id);
            return Partial("ShowInformation", info);
        }






    }
}

MyPersonalWebsite/ServiceHost/Areas/Administration/Pages/Services/Customers/Index.cshtml.cs
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ServiceManagement.Application.Contract.Customers;

namespace ServiceHost.Areas.Administration.Pages.Services.Customers
{
    public class IndexModel : PageModel
    {
        [TempData]
        public string Message { get; set; }

        public List<CustomersViewModel> Customers;

        private readonly ICustomersApplication _customersApplication;

        public IndexModel(ICustomersApplication customersApplication)
        {
            _customersApplication = customersApplication;

        }


        public void OnGet()
        {

            Customers = _customersApplication.GetList();
        }

        public IActionResult OnGetCreate()
        {
            var command = new CreateCustomers();
            return Partial("./Create", command);

        }

        public JsonResult OnPostCreate(CreateCustomers command)
        {
            var result = _customersApplication.Create(command);
            return new JsonResult(result);
        }

        public IActionResult OnGetEdit(long id)
        {
            var slide = _customersApplication.GetDetails(id);
            return Partial("Edit", slide);
        }

        public JsonResult OnPostEdit(EditCustomers command)
        {
            var result = _customersApplication.Edit(command);
            return new JsonResult(result);
        }
    }
}

MyPersonalWebsite/ServiceHost/Areas/Administration/Pages/Services/Plans/Index.cshtml.cs
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ServiceManagement.Application.Contract.Plans;

namespace ServiceHost.Areas.Administration.Pages.Services.Plans
{
    public class IndexModel : PageModel
    {
        [TempData]
        public string Message { get; set; }

        public List<PlansViewModel> Plans;

        private readonly IPlansApplication _plansApplication;

        public IndexModel(IPlansApplication plansApplication)
        {
            _plansApplication = plansApplication;

        }


        public void OnGet()
        {

            Plans = _plansApplication.GetList();
        }

        public IActionResult OnGetCreate()
        {
            var command = new CreatePlans();
            return Partial("./Create", command);

        }

        public JsonResult OnPostCreate(CreatePlans command)
        {
            var result = _plansApplication.Create(command);
            return new JsonResult(result);
        }

        public IActionResult OnGetEdit(long id)
        {
            var slide = _plansApplication.GetDetails(id);
            return Partial("Edit", slide);
        }

        public JsonResult OnPostEdit(EditPlans command)
        {
            var result = _plansApplication.Edit(command);
            return new JsonResult(result);
        }
    }
}

MyPersonalWebsite/ServiceHost/Areas/Administration/Pages/Services/Service/Index.cshtml.cs
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ServiceManagement.Application.Contract.Services;

namespace ServiceHost.Areas.Administration.Pages.Services.Service
{
    public class IndexModel : PageModel
    {
        [TempData]
        public string Message { get; set; }

        public List<ServicesViewModel> Services;

        private readonly IServicesApplication _servicesApplication;

        public IndexModel(IServicesApplication servicesApplication)
        {
            _servicesApplication = servicesApplication;

        }


        public void OnGet()
        {

            Services = _servicesApplication.GetList();
        }

        public IActionResult OnGetCreate()
        {
            var command = new CreateServices();
            return Partial("./Create", command);

        }

        public JsonResult OnPostCreate(CreateServices command)
        {
            var result = _servicesApplication.Create(command);
            return new JsonResult(result);
        }

        public IActionResult OnGetEdit(long id)
        {
            var slide = _servicesApplication.GetDetails(id);
            return Partial("Edit", slide);
        }

        public JsonResult OnPostEdit(EditServices command)
        {
            var result = _servicesApplication.Edit(command);
            return new JsonResult(result);
        }
    }
}

MyPersonalWebsite/ServiceHost/Areas/Administration/Pages/Services/Clients/Create.cshtml
@model ServiceManagement.Application.Contract.ClientsOpinion.CreateClientsOpinion



<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h4 class="modal-title">ایجاد نظر جدید</h4>
</div>

<form asp-page="./Index" asp-page-handler="Create"
      method="post"
      data-ajax="true"
      data-callback=""
      data-action="Refresh"
      enctype="multipart/form-data">
    <div class="modal-body">
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="ClientName" class="control-label">نام مشتری</label>
                    <input type="text" class="form-control" asp-for="ClientName">
                    <span asp-validation-for="ClientName" class="error"></span>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="ClientJob" class="control-label">موقعیت شغلی</label>
                    <input type="text" class="form-control" asp-for="ClientJob">
                    <span asp-validation-for="ClientJob" class="error"></span>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <label asp-for="Description" class="control-label">توضیحات</label>
                <textarea class="form-control autogrow" asp-for="Description"
                          style="overflow: hidden; word-wrap: break-word; resize: horizontal; height: 104px;"></textarea>
                <span asp-validation-for="Description" class="error"></span>
            </div>
        </div>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-default waves-effect" data-dismiss="modal">بستن</button>
        <button type="submit" class="btn btn-info waves-effect waves-light">ایجاد نظر</button>
    </div>
</form>

MyPersonalWebsite/ServiceHost/Areas/Administration/Pages/Services/Clients/Edit.cshtml
@model ServiceManagement.Application.Contract.ClientsOpinion.EditClientsOpinion


<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h4 class="modal-title">ویرایش نظر</h4>
</div>

<form asp-page="./Index" asp-page-handler="Edit"
      method="post"
      data-ajax="true"
      data-callback=""
      data-action="Refresh"
      enctype="multipart/form-data">
    <div class="modal-body">
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="ClientName" class="control-label">نام مشتری</label>
                    <input type="text" class="form-control" asp-for="ClientName">
                    <span asp-validation-for="ClientName" class="error"></span>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="ClientJob" class="control-label">موقعیت شغلی</label>
                    <input type="text" class="form-control" asp-for="ClientJob">
                    <span asp-validation-for="ClientJob" class="error"></span>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <label asp-for="Description" class="control-label">توضیحات</label>
                <textarea class="form-control autogrow" asp-for="Description"
                          style="overflow: hidden; word-wrap: break-word; resize: horizontal; height: 104px;"></textarea>
                <span asp-validation-for="Description" class="error"></span>
            </div>
        </div>
        <input type="hidden" asp-for="Id" />
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-default waves-effect" data-dismiss="modal">بستن</button>
        <button type="submit" class="btn btn-warning waves-effect waves-light">ویرایش نظر</button>
    </div>
</form>

MyPersonalWebsite/ServiceHost/Areas/Administration/Pages/Services/Clients/Index.cshtml
@page
@model ServiceHost.Areas.Administration.Pages.Services.Clients.IndexModel



@{
    Layout = "Shared/_AdminLayout";
    ViewData["title"] = "مدیریت نظرات مشتریان";
}
<div class="content">
    <div class="row">
        <div class="col-sm-12">
            <h4 class="page-title pull-right">@ViewData["title"]</h4>
            <p class="pull-left">
                <a class="btn btn-success btn-lg" href="#showmodal=@Url.Page("./Index", "Create")" onclick="$('.modal-dialog').css('width','70%')">ایجاد نظر جدید</a>
            </p>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">لیست نظرات مشتریان</h3>
                </div>
                <div class="panel-body">
                    <div class="row">
                        <div class="col-md-12 col-sm-12 col-xs-12">
                            <table id="datatable" class="table table-striped table-bordered">
                                <thead>
                                    <tr>
                                        <th>#</th>
                                        <th>نام مشتری</th>
                                        <th>موقعیت شغلی</th>
                                        <th>متن نظر</th>
                                        <th>وضعیت</th>
                                        <th>تاریخ ایجاد</th>
                                        <th>عملیات</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var item in Model.ClientsOpinion)
                                    {
                                    <tr>
                                        <td>@item.Id</td>
                                        <td>@item.ClientName</td>
                                        <td>@item.ClientJob</td>
                                        <td>@item.Description</td>
                                        <td class="text-center">
                                        @if (!item.IsRemoved)
                                        {
                                            <i class="fa fa-check fa-3x text-success"></i>
                                        }
                                        else
                                        {
                                            <i class="fa fa-remove fa-3x text-danger"></i>
                                        }
                                        <td>@item.CreationDate</td>
                                        <td>
                                            <a class="btn btn-warning btn-rounded waves-effect waves-light m-b-5"
                                               href="#showmodal=@Url.Page("./Index", "Edit", new { id = item.Id})" onclick="$('.modal-dialog').css('width','70%')">
                                                <i class="fa fa-edit"></i> ویرایش
                                            </a>
                                            @if (!item.IsRemoved)
                                            {
                                                <a asp-page="./Index" asp-page-handler="Remove" asp-route-id="@item.Id"
                                                   class="btn btn-danger btn-rounded waves-effect waves-light m-b-5">عدم نمایش</a>
                                            }
                                            else
                                            {
                                                <a asp-page="./Index" asp-page-handler="Restore" asp-route-id="@item.Id"
                                                   class="btn btn-success btn-rounded waves-effect waves-light m-b-5">نمایش</a>
                                            }
                                        </td>
                                    </tr>
                                    }
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    <script src="~/adminTheme/assets/datatables/jquery.dataTables.min.js"></script>
    <script src="~/adminTheme/assets/datatables/dataTables.bootstrap.js"></script>

    <script type="text/javascript">
        $(document).ready(function () {
            $('#datatable').dataTable();
        });
    </script>
}